-- Version 2 Oct 10th, 2013.  
-- 		Had to modify all 'IN' statements that were dealing with numbers.  IN's evidently don't work with floats.  ... and may not work with integers
-- Version 2.1
--		Added two new INSERT Queries to account for Jims new Overall spreadsheet.  'Overall_Wes_13Nov27th.xlxs.'
-- Version 2.2
--		Modified Queries 15 & 16 to change an = to an RLIKE.  This was to account for an apostrophe in the string contents of Subgroup.
-- Version 3.0
-- 		Remade join with ODL specifications using individual queries based on Jim A's spreadsheet

USE ODL;

UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.25 - 0.03  AND 0.25 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.25 - 0.03  AND 0.25 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-S' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-S' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-S' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.29 - 0.03  AND 0.29 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.29 - 0.03  AND 0.29 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'S' AND MPC_Parsed_LtSize IN ('3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'S' AND MPC_Parsed_LtSize IN ('Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$') AND MPC NOT RLIKE '.*iron.*';
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'OF-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'SS-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity doorglass Rectangles' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.758 - 0.03  AND 0.758 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'SS-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.0367, 0.0366, 0, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');

UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity Glass Ovals & Roundtops' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.25 - 0.03  AND 0.25 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A8-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity Glass Ovals & Roundtops' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.25 - 0.03  AND 0.25 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A8-S' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','1/2','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity Glass Ovals & Roundtops' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.625 - 0.03  AND 0.625 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A8-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('3/4')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity Glass Ovals & Roundtops' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A8-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity Glass Ovals & Roundtops' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A8-S' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Commodity doorglass:  1-Lites GBGs external grilles', subgroup = 'Commodity Glass Ovals & Roundtops' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A8-S' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');

UPDATE odl_raw SET glass_type = 'Simulated Divided Lite', subgroup = 'Simulated Divided Lite' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Simulated Divided Lite', subgroup = 'Simulated Divided Lite' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.813 - 0.03  AND 0.813 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-S' AND grid = 'S' AND MPC_Parsed_LtSize IN ('1/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');

UPDATE odl_raw SET glass_type = 'Decorative', subgroup = 'Deco Rectangular Frame' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.313 - 0.03  AND 0.313 + 0.03  AND Gap_Width_Str2 BETWEEN 0.313 - 0.03 AND 0.313 + 0.03 AND Spacer = 'A5-S' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.0367, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Decorative', subgroup = 'Deco Rectangular Frame' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.313 - 0.03  AND 0.313 + 0.03  AND Gap_Width_Str2 BETWEEN 0.313 - 0.03 AND 0.313 + 0.03 AND Spacer = 'A1-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.0367, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Decorative', subgroup = 'Deco Rectangular Frame' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.313 - 0.03  AND 0.313 + 0.03  AND Gap_Width_Str2 BETWEEN 0.313 - 0.03 AND 0.313 + 0.03 AND Spacer = 'A1-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.0367, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Decorative', subgroup = 'Deco Rectangular Frame' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.313 - 0.03  AND 0.313 + 0.03  AND Gap_Width_Str2 BETWEEN 0.313 - 0.03 AND 0.313 + 0.03 AND Spacer = 'ZF-S' AND grid = 'G' AND MPC_Parsed_LtSize IN ('Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.0367, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');

UPDATE odl_raw SET glass_type = 'Decorative', subgroup = 'Oval Deco' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.243 - 0.03  AND 0.243 + 0.03  AND Gap_Width_Str2 BETWEEN 0.243 - 0.03 AND 0.243 + 0.03 AND Spacer = 'A5-S' AND grid = 'G' AND MPC_Parsed_LtSize IN ('3/4')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Decorative', subgroup = 'Oval Deco' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.313 - 0.03  AND 0.313 + 0.03  AND Gap_Width_Str2 BETWEEN 0.313 - 0.03 AND 0.313 + 0.03 AND Spacer = 'A5-S' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/2','3/4')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');

UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Severe Weather Deco' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.205 - 0.03  AND 0.205 + 0.03  AND Gap_Width_Str2 BETWEEN 0.205 - 0.03 AND 0.205 + 0.03 AND Spacer = 'A5-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';

UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. Weather 1-Lites GBGs' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';
UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. Weather 1-Lites GBGs' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.509 - 0.03  AND 0.509 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476, 0.068) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';
UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. Weather 1-Lites GBGs' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.509 - 0.03  AND 0.509 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476, 0.068) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';
UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. Weather 1-Lites GBGs' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.509 - 0.03  AND 0.509 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';

UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. W. Internal Wrought Iron' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.535 - 0.03  AND 0.535 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A5-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';
UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. W. Internal Wrought Iron' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.535 - 0.03  AND 0.535 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A5-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';

UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. Weather Blind' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.813 - 0.03  AND 0.813 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/2','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476, 0.068) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';
UPDATE odl_raw SET glass_type = 'Severe Weather Impact-rated ', subgroup = 'Sev. Weather Blind' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.813 - 0.03  AND 0.813 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/2','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476, 0.068) AND (MPC RLIKE '^.*LAMI?.*$' OR MPC RLIKE '^.*IMP.*$') AND MPC NOT RLIKE '.*[Non]?ImpDoor.*';

UPDATE odl_raw SET glass_type = 'Blinds', subgroup = 'Dual Glazed Blind' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.813 - 0.03  AND 0.813 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/2','3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.0367, 0.037) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Blinds', subgroup = 'Triple Glazed Blind' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0.813 - 0.03 AND 0.813 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/2','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Blinds', subgroup = 'Triple Glazed Blind' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0.813 - 0.03 AND 0.813 + 0.03 AND Spacer = 'CU-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/2','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Blinds', subgroup = 'Triple Glazed Blind' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0.813 - 0.03 AND 0.813 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/2','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Blinds', subgroup = 'Triple Glazed Blind' WHERE glass_type IS NULL AND GL = 3 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0.813 - 0.03 AND 0.813 + 0.03 AND Spacer = 'CU-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/2','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');

UPDATE odl_raw SET glass_type = 'Internal & External Wrought Iron', subgroup = 'Internal Wrought Iron' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A5-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/4','1/2','3/4')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*IRON.*$' OR MPC RLIKE '^.*Iron.*$');
UPDATE odl_raw SET glass_type = 'Internal & External Wrought Iron', subgroup = 'Internal Wrought Iron' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0) AND (MPC RLIKE '^.*IRON.*$' OR MPC RLIKE '^.*Iron.*$');

UPDATE odl_raw SET glass_type = 'Internal & External Wrought Iron', subgroup = 'External Wrought Iron' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.75 - 0.03  AND 0.75 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('3/4','Full')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');

UPDATE odl_raw SET glass_type = 'Vent', subgroup = 'Vent 22x36' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A8-S' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Vent', subgroup = 'Vent 22x36' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'A1-S' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Vent', subgroup = 'Vent 22x36' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'N' AND MPC_Parsed_LtSize IN ('1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');
UPDATE odl_raw SET glass_type = 'Vent', subgroup = 'Vent 22x36' WHERE glass_type IS NULL AND GL = 2 AND Gap_Width_Str1 BETWEEN 0.5 - 0.03  AND 0.5 + 0.03  AND Gap_Width_Str2 BETWEEN 0 - 0.03 AND 0 + 0.03 AND Spacer = 'CU-D' AND grid = 'G' AND MPC_Parsed_LtSize IN ('1/2')  AND cast(low_e_str1 as DECIMAL(6,4)) IN (0, 0.148, 0.1476) AND (MPC RLIKE '^.*$' OR MPC RLIKE '^.*$');


-- -------------------------------------------------------------------------
-- Create new table odl_filtered based on built up info from UID's for keep.
-- -------------------------------------------------------------------------
DROP TABLE IF EXISTS ODL_Filtered;
CREATE TABLE ODL_Filtered AS (
	SELECT DISTINCT * FROM odl_raw r
		WHERE glass_type is not null
		ORDER BY -- CPD asc ; -- treating numbers as numbers and text as text
			substring_index(cpd, '-', 1),
			substring_index(substring_index(cpd, '-', 2), '-', -1),
			cast(substring_index(substring_index(cpd, ' ', 1), '-', -1) as unsigned int),
			cast(substring_index(substring_index(cpd, ' ', -1), '-', 1) as unsigned int),
			cast(substring_index(substring_index(cpd, ' ', -1), '-', -1) as unsigned int)	
		);
		
ALTER TABLE odl_filtered
	ADD COLUMN One  tinyint(1) UNSIGNED NULL DEFAULT 1 AFTER UID,	
	ADD COLUMN Row	int	UNSIGNED NOT NULL DEFAULT 0 AFTER One,
	ADD PRIMARY KEY (CPD);
	
UPDATE odl_filtered  -- Adds row number for ranking purposes.
	JOIN (SELECT @curRow :=  0)t1
	SET Row = @curRow := @curRow + 1;

UPDATE odl_filtered SET MPC = replace( replace(MPC, ',', ''), '"', '' );
UPDATE odl_filtered SET Series = replace( replace(Series, ',', ''), '"', '' );
UPDATE odl_filtered SET Series_Concat = replace( replace(Series_Concat, ',', ''), '"', '' );
UPDATE odl_filtered SET MPC = REPLACE(MPC, ',', ' ');


-- ---------------------------------------------------------------------------
-- Clean up.  Removing Items that Jim doesn't want.  See email of 9/22.
-- ---------------------------------------------------------------------------
DELETE FROM odl_filtered WHERE MPC RLIKE '^.*71/38.*$';
DELETE FROM odl_filtered WHERE glass_type = 'Vent' AND spacer_name LIKE '%Intercept';
DELETE FROM odl_filtered WHERE manufacturer_code = 'THC';
